package com.dynatrace.wizard.wizard

import com.dynatrace.wizard.model.DynatraceConfig
import com.dynatrace.wizard.util.DocumentationLinks
import com.dynatrace.wizard.util.WizardColors
import com.intellij.ui.TitledSeparator
import com.intellij.ui.components.JBCheckBox
import com.intellij.ui.components.JBLabel
import com.intellij.ui.components.JBTextField
import com.intellij.util.ui.FormBuilder
import com.intellij.util.ui.JBUI
import com.intellij.util.ui.UIUtil
import java.awt.BorderLayout
import java.awt.Dimension
import javax.swing.JComponent
import javax.swing.JPanel

/**
 * Step 3 of the wizard: Feature toggles for Dynatrace instrumentation options.
 */
class FeatureToggleStep {

    // --- Global ---
    val pluginEnabledCheckBox = JBCheckBox("Plugin enabled (uncheck to disable all auto-instrumentation)", true)

    // --- Instrumentation ---
    val autoInstrumentCheckBox = JBCheckBox("Enable auto-instrumentation (bytecode transform)", true)
    val autoStartEnabledCheckBox = JBCheckBox("Auto-start OneAgent on app launch", true)

    // --- Monitoring sections ---
    val userActionsCheckBox = JBCheckBox("User action monitoring", true)
    val webRequestsCheckBox = JBCheckBox("Web request monitoring", true)
    val lifecycleCheckBox = JBCheckBox("Lifecycle monitoring", true)
    val crashReportingCheckBox = JBCheckBox("Crash reporting", true)

    // --- Compose & Behavioral ---
    val composeEnabledCheckBox = JBCheckBox("Jetpack Compose auto-instrumentation", true)
    val rageTapCheckBox = JBCheckBox("Rage tap detection", false)

    // --- Privacy ---
    val userOptInCheckBox = JBCheckBox("User opt-in mode (require explicit consent)", false)
    val namePrivacyCheckBox = JBCheckBox("Name privacy — mask autogenerated action names (PII)", false)
    val locationMonitoringCheckBox = JBCheckBox("Location monitoring", false)
    val hybridMonitoringCheckBox = JBCheckBox("Hybrid monitoring (WebView)", false)

    // --- Advanced agent behavior ---
    val agentBehaviorLbCheckBox = JBCheckBox("Client-side load balancing across ActiveGates", false)
    val agentBehaviorGrailCheckBox = JBCheckBox("Enable New RUM Experience on first start", false)
    val strictModeCheckBox = JBCheckBox("Strict mode (fail build if variant has no config)", false)

    // --- Session Replay ---
    val sessionReplayCheckBox = JBCheckBox("Session Replay (record screen content)", false)

    // --- Exclusions ---
    val excludePackagesField = JBTextField()
    val excludeClassesField = JBTextField()
    val excludeMethodsField = JBTextField()

    // --- Build variant ---
    val buildVariantField = JBTextField()

    private val instrumentationStatusLabel = JBLabel().apply {
        font = JBUI.Fonts.smallFont()
        foreground = UIUtil.getContextHelpForeground()
    }

    private val autoInstrumentationDependents by lazy {
        listOf<JComponent>(
            userActionsCheckBox,
            webRequestsCheckBox,
            lifecycleCheckBox,
            composeEnabledCheckBox,
            rageTapCheckBox,
            excludePackagesField,
            excludeClassesField,
            excludeMethodsField
        )
    }

    fun createPanel(): JComponent {
        excludePackagesField.emptyText.setText("e.g. com.example.analytics, com.third.party")
        excludeClassesField.emptyText.setText("e.g. com.example.HeavyClass")
        excludeMethodsField.emptyText.setText("e.g. com.example.Util.expensiveMethod")
        buildVariantField.emptyText.setText("Leave empty or 'all' for all variants")

        pluginEnabledCheckBox.addActionListener { syncFeatureAvailability() }
        autoInstrumentCheckBox.addActionListener { syncFeatureAvailability() }

        val panel = FormBuilder.createFormBuilder()
            .addComponent(
                JBLabel("Feature Configuration").apply {
                    font = JBUI.Fonts.label(16f).asBold()
                    foreground = WizardColors.accent
                    border = JBUI.Borders.emptyBottom(2)
                }
            )
            .addComponent(
                JBLabel("Enable or disable individual instrumentation capabilities.").apply {
                    foreground = UIUtil.getContextHelpForeground()
                    border = JBUI.Borders.emptyBottom(4)
                }
            )
            .addComponent(instrumentationStatusLabel.apply { border = JBUI.Borders.emptyBottom(4) })
            // ── Global ────────────────────────────────────────────────────────
            .addComponent(TitledSeparator("Global"))
            .addComponent(checkboxItem(pluginEnabledCheckBox,
                "Unchecking disables bytecode instrumentation but keeps the OneAgent SDK dependency."))
            // ── Instrumentation ───────────────────────────────────────────────
            .addComponent(TitledSeparator("Instrumentation"))
            .addComponent(checkboxItem(autoInstrumentCheckBox,
                "Transforms bytecode at compile time for automatic capture of HTTP, lifecycle, and Compose events."))
            .addVerticalGap(4)
            .addComponent(checkboxItem(autoStartEnabledCheckBox,
                "OneAgent auto-starts in Application.onCreate. Disable for Direct Boot apps — " +
                "a manual startup snippet will be shown in the summary."))
            // ── Monitoring Sections ───────────────────────────────────────────
            .addComponent(TitledSeparator("Monitoring Sections"))
            .addComponent(checkboxItem(userActionsCheckBox,
                "Track user taps, swipes, and Compose interactions."))
            .addVerticalGap(4)
            .addComponent(checkboxItem(webRequestsCheckBox,
                "Monitor HttpURLConnection, OkHttp v3/4/5 requests automatically."))
            .addVerticalGap(4)
            .addComponent(checkboxItem(lifecycleCheckBox,
                "Track Activity/Fragment display and app start events."))
            .addVerticalGap(4)
            .addComponent(checkboxItem(crashReportingCheckBox,
                "Capture uncaught exceptions with full stack traces (not sent if older than 10 min)."))
            // ── Compose & Behavioral Events ───────────────────────────────────
            .addComponent(TitledSeparator("Compose & Behavioral Events"))
            .addComponent(checkboxItem(composeEnabledCheckBox,
                "Enabled by default from plugin 8.271+. Instruments Compose clickable, " +
                "swipeable, slider, pager, and pull-refresh."))
            .addVerticalGap(4)
            .addComponent(checkboxItem(rageTapCheckBox,
                "Detect frustrated users repeatedly tapping an unresponsive area."))
            // ── Privacy ───────────────────────────────────────────────────────
            .addComponent(TitledSeparator("Privacy"))
            .addComponent(checkboxItem(userOptInCheckBox,
                "Require explicit user consent before collecting data (GDPR). " +
                "No data is sent until the app calls the OneAgent SDK opt-in API."))
            .addVerticalGap(4)
            .addComponent(checkboxItem(namePrivacyCheckBox,
                "Masks autogenerated user action names to prevent PII leakage. " +
                "Available from plugin 8.249+. Reduces Compose metadata captured."))
            .addVerticalGap(4)
            .addComponent(checkboxItem(locationMonitoringCheckBox,
                "Appends already-processed location data (truncated to ~1 km). " +
                "OneAgent will NOT request location permissions."))
            .addVerticalGap(4)
            .addComponent(checkboxItem(hybridMonitoringCheckBox,
                "Monitor web content in WebViews (requires Dynatrace JS agent on your pages)."))
            // ── Advanced ──────────────────────────────────────────────────────
            .addComponent(TitledSeparator("Advanced"))
            .addComponent(checkboxItem(agentBehaviorLbCheckBox,
                "Enables client-side load balancing between multiple ActiveGates at startup."))
            .addVerticalGap(4)
            .addComponent(checkboxItem(agentBehaviorGrailCheckBox,
                "Activates New RUM Experience (Grail) on first app start " +
                "(can be overridden by cluster config)."))
            .addVerticalGap(4)
            .addComponent(checkboxItem(strictModeCheckBox,
                "When enabled the build fails if a variant has no matching Dynatrace config — " +
                "forces full coverage."))
            // ── Session Replay ────────────────────────────────────────────────
            .addComponent(TitledSeparator("Session Replay"))
            .addComponent(checkboxItem(sessionReplayCheckBox,
                "Records screen content and user interactions for visual session playback. " +
                "Requires a Session Replay license. Emits sessionReplay.enabled(true) — " +
                "available from plugin 8.281+."))
            // ── Exclusions ────────────────────────────────────────────────────
            .addComponent(TitledSeparator("Exclusions (comma-separated)"))
            .addLabeledComponent(JBLabel("Exclude packages:"),
                fieldWithHint(excludePackagesField,
                    "Skips all classes in the listed packages."), true)
            .addVerticalGap(4)
            .addLabeledComponent(JBLabel("Exclude classes:"),
                fieldWithHint(excludeClassesField,
                    "Skips specific fully-qualified class names."), true)
            .addVerticalGap(4)
            .addLabeledComponent(JBLabel("Exclude methods:"),
                fieldWithHint(excludeMethodsField,
                    "Use \$ to escape inner classes, e.g. com.example.Outer\$Inner."), true)
            // ── Build Variant ─────────────────────────────────────────────────
            .addComponent(TitledSeparator("Build Variant"))
            .addLabeledComponent(JBLabel("Variant filter:"),
                fieldWithHint(buildVariantField,
                    "Restrict instrumentation to a specific variant (regex). " +
                    "Leave blank for all variants."), true)
            // ── Documentation ─────────────────────────────────────────────────
            .addComponent(TitledSeparator("Documentation"))
            .addComponent(DocumentationLinks.createLinkLabel("Configure Plugin for Instrumentation", DocumentationLinks.CONFIGURE_PLUGIN))
            .addComponent(DocumentationLinks.createLinkLabel("Monitoring Capabilities", DocumentationLinks.MONITORING_CAPABILITIES))
            .addComponent(DocumentationLinks.createLinkLabel("Crash Reporting", DocumentationLinks.CRASH_REPORTING))
            .addComponent(DocumentationLinks.createLinkLabel("User Privacy & Opt-In", DocumentationLinks.USER_OPT_IN))
            .addComponent(DocumentationLinks.createLinkLabel("Adjust OneAgent Configuration", DocumentationLinks.ADJUST_ONEAGENT))
            .addComponent(DocumentationLinks.createLinkLabel("Multi-Module Projects", DocumentationLinks.MULTI_MODULE))
            .addVerticalGap(8)
            .panel
            .also { it.border = JBUI.Borders.empty(8, 12, 12, 12) }

        syncFeatureAvailability()
        return panel
    }

    // ── Helpers ───────────────────────────────────────────────────────────────

    /**
     * Returns a panel that visually groups a checkbox and its explanatory hint
     * into a single cohesive component. The hint wraps at dialog width.
     */
    private fun checkboxItem(checkBox: JBCheckBox, hint: String): JComponent =
        JPanel(BorderLayout()).apply {
            isOpaque = false
            add(checkBox, BorderLayout.NORTH)
            add(JBLabel("<html>$hint</html>").apply {
                font = JBUI.Fonts.smallFont()
                foreground = UIUtil.getContextHelpForeground()
                border = JBUI.Borders.empty(1, JBUI.scale(20), 4, 0)
            }, BorderLayout.CENTER)
        }

    /**
     * Returns a panel stacking a text field above a small hint label.
     * The field expands to full width; the hint text wraps automatically.
     */
    private fun fieldWithHint(field: JBTextField, hint: String): JComponent =
        JPanel(BorderLayout(0, JBUI.scale(2))).apply {
            isOpaque = false
            field.maximumSize = Dimension(Int.MAX_VALUE, field.preferredSize.height)
            add(field, BorderLayout.NORTH)
            add(JBLabel("<html>$hint</html>").apply {
                font = JBUI.Fonts.smallFont()
                foreground = UIUtil.getContextHelpForeground()
            }, BorderLayout.CENTER)
        }

    private fun syncFeatureAvailability() {
        val pluginEnabled = pluginEnabledCheckBox.isSelected
        autoInstrumentCheckBox.isEnabled = pluginEnabled

        val autoInstrumentationActive = pluginEnabled && autoInstrumentCheckBox.isSelected
        autoInstrumentationDependents.forEach { it.isEnabled = autoInstrumentationActive }

        instrumentationStatusLabel.text = when {
            !pluginEnabled ->
                "Plugin setup remains in the generated Gradle files, but automatic capture options are paused until Plugin enabled is turned back on."
            !autoInstrumentCheckBox.isSelected ->
                "Auto-instrumentation is turned off. Monitoring toggles and exclusions are kept for later, but they are inactive until auto-instrumentation is re-enabled."
            else ->
                "Recommended setup is active: automatic capture is enabled, and the monitoring options below will be applied as selected."
        }
    }

    // ── Public API ────────────────────────────────────────────────────────────

    fun isPluginEnabled(): Boolean = pluginEnabledCheckBox.isSelected
    fun isAutoInstrument(): Boolean = autoInstrumentCheckBox.isSelected
    fun isAutoStartEnabled(): Boolean = autoStartEnabledCheckBox.isSelected
    fun isUserActionsEnabled(): Boolean = userActionsCheckBox.isSelected
    fun isWebRequestsEnabled(): Boolean = webRequestsCheckBox.isSelected
    fun isLifecycleEnabled(): Boolean = lifecycleCheckBox.isSelected
    fun isCrashReporting(): Boolean = crashReportingCheckBox.isSelected
    fun isComposeEnabled(): Boolean = composeEnabledCheckBox.isSelected
    fun isRageTapDetection(): Boolean = rageTapCheckBox.isSelected
    fun isUserOptIn(): Boolean = userOptInCheckBox.isSelected
    fun isNamePrivacy(): Boolean = namePrivacyCheckBox.isSelected
    fun isLocationMonitoring(): Boolean = locationMonitoringCheckBox.isSelected
    fun isHybridMonitoring(): Boolean = hybridMonitoringCheckBox.isSelected
    fun isAgentBehaviorLoadBalancing(): Boolean = agentBehaviorLbCheckBox.isSelected
    fun isAgentBehaviorGrail(): Boolean = agentBehaviorGrailCheckBox.isSelected
    fun isStrictMode(): Boolean = strictModeCheckBox.isSelected
    fun isSessionReplayEnabled(): Boolean = sessionReplayCheckBox.isSelected
    fun getExcludePackages(): String = excludePackagesField.text.trim()
    fun getExcludeClasses(): String = excludeClassesField.text.trim()
    fun getExcludeMethods(): String = excludeMethodsField.text.trim()
    fun getBuildVariant(): String = buildVariantField.text.trim().ifBlank { "all" }

    /** Pre-fills all controls with values from an existing Dynatrace configuration. */
    fun prefill(config: DynatraceConfig) {
        pluginEnabledCheckBox.isSelected        = config.pluginEnabled
        autoInstrumentCheckBox.isSelected       = config.autoInstrument
        autoStartEnabledCheckBox.isSelected     = config.autoStartEnabled
        userActionsCheckBox.isSelected          = config.userActionsEnabled
        webRequestsCheckBox.isSelected          = config.webRequestsEnabled
        lifecycleCheckBox.isSelected            = config.lifecycleEnabled
        crashReportingCheckBox.isSelected       = config.crashReporting
        composeEnabledCheckBox.isSelected       = config.composeEnabled
        rageTapCheckBox.isSelected              = config.rageTapDetection
        userOptInCheckBox.isSelected            = config.userOptIn
        namePrivacyCheckBox.isSelected          = config.namePrivacy
        locationMonitoringCheckBox.isSelected   = config.locationMonitoring
        hybridMonitoringCheckBox.isSelected     = config.hybridMonitoring
        agentBehaviorLbCheckBox.isSelected      = config.agentBehaviorLoadBalancing
        agentBehaviorGrailCheckBox.isSelected   = config.agentBehaviorGrail
        strictModeCheckBox.isSelected           = config.strictMode
        sessionReplayCheckBox.isSelected        = config.sessionReplayEnabled
        excludePackagesField.text               = config.excludePackages
        excludeClassesField.text                = config.excludeClasses
        excludeMethodsField.text                = config.excludeMethods
        buildVariantField.text                  = if (config.buildVariant == "all") "" else config.buildVariant
        syncFeatureAvailability()
    }
}
